# Generated by Django 2.2.8 on 2020-09-12 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0029_auto_20200625_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 13, 36, 50, 203665, tzinfo=utc), max_length=255),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 13, 36, 50, 203693, tzinfo=utc), max_length=255),
        ),
    ]
